import SwiftUI
import AppKit

struct PurgeView: View {
    @State private var hits: [PurgeHit] = []
    @State private var roots: [String] = PurgeService.defaultScanPaths()
    @State private var scanning = false
    @State private var working = false
    @State private var log = ""
    @State private var newRoot = ""
    @State private var showConfirm = false

    var selected: [PurgeHit] { hits.filter { $0.selected } }
    var totalBytes: Int64 { selected.map { $0.size }.reduce(0, +) }

    var body: some View {
        VStack(spacing: 12) {
            rootsToolbar
            scanToolbar
            content
        }
        .padding(16)
        .navigationTitle("Project Purge")
        .alert("Move \(selected.count) artifact(s) to Trash?", isPresented: $showConfirm) {
            Button("Cancel", role: .cancel) {}
            Button("Move to Trash", role: .destructive) { applyPurge() }
        } message: {
            Text("Total \(byteString(totalBytes)). Build artifacts can be regenerated by your build tool.")
        }
    }

    private var rootsToolbar: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Scan roots").font(.caption).foregroundStyle(.secondary)
            HStack(spacing: 6) {
                ForEach(roots, id: \.self) { r in
                    HStack(spacing: 4) {
                        Text((r as NSString).abbreviatingWithTildeInPath).font(.system(.caption, design: .monospaced))
                        Button { roots.removeAll { $0 == r } } label: { Image(systemName: "xmark.circle.fill") }.buttonStyle(.plain)
                    }
                    .padding(.horizontal, 6).padding(.vertical, 3)
                    .background(.background.tertiary, in: .capsule)
                }
                TextField("Add path…", text: $newRoot)
                    .textFieldStyle(.roundedBorder).frame(width: 200)
                    .onSubmit { addRoot() }
                Button("Add") { addRoot() }.disabled(newRoot.isEmpty)
                Button("Pick…") { pickRoot() }
            }
        }
    }

    private var scanToolbar: some View {
        HStack {
            Button { Task { await scan() } } label: {
                Label(scanning ? "Scanning…" : "Scan", systemImage: "magnifyingglass")
            }.buttonStyle(.borderedProminent).disabled(scanning || working || roots.isEmpty)
            Button {
                let allOn = hits.allSatisfy { $0.selected }
                for i in hits.indices { hits[i].selected = !allOn }
            } label: { Label("Toggle All", systemImage: "checkmark.square") }.disabled(hits.isEmpty)
            Spacer()
            Text("\(hits.count) found · \(selected.count) sel · \(byteString(totalBytes))").foregroundStyle(.secondary)
            Button(role: .destructive) { showConfirm = true } label: {
                Label("Move Selected to Trash", systemImage: "trash")
            }
            .buttonStyle(.borderedProminent).tint(.red)
            .disabled(selected.isEmpty || working)
        }
    }

    private var content: some View {
        HSplitView {
            List {
                if hits.isEmpty && !scanning {
                    Text("Add roots above and click Scan. Mole's purge looks for: node_modules, target, build, dist, .gradle, .next, DerivedData, Pods, .dart_tool, etc.")
                        .foregroundStyle(.secondary).padding()
                } else {
                    ForEach(hits) { hit in
                        HStack {
                            Toggle("", isOn: bindingFor(hit)).labelsHidden()
                            VStack(alignment: .leading) {
                                Text(hit.kind).fontWeight(.medium).foregroundStyle(kindColor(hit.kind))
                                Text((hit.path as NSString).abbreviatingWithTildeInPath)
                                    .font(.system(.caption, design: .monospaced)).foregroundStyle(.secondary)
                                    .lineLimit(1).truncationMode(.middle)
                            }
                            Spacer()
                            Text(byteString(hit.size)).font(.system(.body, design: .monospaced))
                                .foregroundStyle(hit.size > 1_073_741_824 ? .red : (hit.size > 104_857_600 ? .orange : .secondary))
                                .frame(width: 90, alignment: .trailing)
                        }
                        .padding(.vertical, 2)
                        .contentShape(.rect)
                        .onTapGesture { toggle(hit) }
                    }
                }
            }
            .frame(minWidth: 540)

            VStack(alignment: .leading, spacing: 8) {
                Text("Log").font(.headline)
                LogPane(placeholder: "No operations yet.", log: log)
            }
            .padding(.leading, 8)
            .frame(minWidth: 280)
        }
    }

    private func bindingFor(_ hit: PurgeHit) -> Binding<Bool> {
        Binding(
            get: { hits.first(where: { $0.id == hit.id })?.selected ?? false },
            set: { v in if let i = hits.firstIndex(where: { $0.id == hit.id }) { hits[i].selected = v } }
        )
    }

    private func toggle(_ hit: PurgeHit) {
        if let i = hits.firstIndex(where: { $0.id == hit.id }) { hits[i].selected.toggle() }
    }

    private func kindColor(_ kind: String) -> Color {
        switch kind {
        case "node_modules": return .green
        case "target", "build", ".build", "DerivedData", ".gradle": return .blue
        case ".next", ".nuxt", ".turbo", "dist": return .purple
        case "vendor": return .orange
        case "Pods": return .pink
        default: return .primary
        }
    }

    private func addRoot() {
        let p = newRoot.trimmingCharacters(in: .whitespaces)
        guard !p.isEmpty else { return }
        let exp = (p as NSString).expandingTildeInPath
        if FileManager.default.fileExists(atPath: exp), !roots.contains(exp) {
            roots.append(exp)
        }
        newRoot = ""
    }

    private func pickRoot() {
        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        if panel.runModal() == .OK, let url = panel.url {
            if !roots.contains(url.path) { roots.append(url.path) }
        }
    }

    private func byteString(_ b: Int64) -> String {
        let f = ByteCountFormatter(); f.countStyle = .file
        return f.string(fromByteCount: b)
    }

    @MainActor
    private func scan() async {
        scanning = true
        hits.removeAll()
        log = "Scanning \(roots.count) root(s)…\n"
        let result = await PurgeService.scan(roots: roots)
        hits = result
        scanning = false
        log += "Found \(result.count) artifact(s) — \(byteString(result.map { $0.size }.reduce(0, +))) total\n"
    }

    private func applyPurge() {
        let chosen = selected
        working = true
        log += "\nMoving \(chosen.count) item(s) to Trash…\n"
        Task {
            let result = await PurgeService.purge(chosen)
            await MainActor.run {
                log += result
                working = false
                hits.removeAll { h in chosen.contains(where: { $0.id == h.id }) }
            }
        }
    }
}
